server:
  port: 8761
eureka:  
  client:    
    register-with-eureka: false
    fetch-registry: false #false:doesn't take as a micro service
  server:    
    wait-time-in-ms-when-sync-empty: 0
spring:  
  application:    
    name: common-server   